= Recommended upgrade
:toc: right
:imagesdir: media/
:sourcedir: ../src/main/resources/
:snippet: ../../code-samples/code-snippets/

== Step by step

This describes upgrading to the full feature set of react4xp 6 including migrating pages and layouts to react.

. Create an app using the link:../setup#create-starter[starter^] and give it a new name.
. <<migrating-parts, Migrate>> each react component to the new app.
. Migrate your <<migrate-page, page>> and <<migrate-layout, layout>> to react components
. link:./legacy#build-deploy[Deploy^] the application on your existing site.

You will now have one application with your schemas, and one containing your frontend.
If you prefer having a single application, follow these steps:

. Move the cms schemas and other files you want to keep to the new application.
. Rename it to the same name as your old application.
. Make a production build and link:./legacy#build-deploy[Deploy^] it.
. The old application can now be discarded.

[[migrating-parts]]
== Migrating parts

Now let’s go a little bit deeper and use the example component as a part along with our new components.
To do this we need to do the following:

. Make an xml file for it so XP knows that it exists, here we can also give it a good description.
+
.src/main/resources/site/parts/example/example.xml
[code,xml]
----
include::{snippet}appendix/upgrade/example.xml[]
----

. Move the example component to the parts folder, where we update it by wrapping it in a `Part` tag instead of `div`.
Then we add extraProps to it, this is important because react4xp v6 uses this to add necessary props to the parts component so it is possible to view and edit it within the page editor.
+
.src/main/resources/react4xp/components/parts/example/example.tsx
[code,TypeScript]
----
include::{snippet}appendix/upgrade/example.tsx[]
----

. Instead of fetching in get(), create a processor that returns its props—React4xp will forward them (plus its own metadata) into <Part> via extraProps.
+
.src/main/resources/react4xp/components/parts/example/exampleProcessor.ts
[code,TypeScript]
----
include::{snippet}appendix/upgrade/exampleProcessor.ts[]
----

. Add it to the componentRegistry and dataFetcher with the same descriptor as in previous task.
+
.src/main/resources/react4xp/componentRegistry.ts
[code,TypeScript]
----
include::{snippet}appendix/upgrade/componentRegistry.tsx[]
----
+
.src/main/resources/react4xp/dataFetcher.ts
[code,TypeScript]
----
include::{snippet}appendix/upgrade/dataFetcher.ts[]
----

[[page-layout]]
[[migrate-page]]
== Pages

Your current page part might look something like this:

.src/main/resources/site/pages/default/default.tsx
[code,typeScript]
----
include::{snippet}appendix/upgrade/pages/pagev5/default.tsx[]
----

with a controller like this:

.src/main/resources/site/pages/default/default.ts
[code,TypeScript]
----
include::{snippet}appendix/upgrade/pages/pagev5/default.ts[]
----

And an xml like this:
.src/main/resources/site/pages/default/default.xml

[code,xml]
----
include::{snippet}appendix/upgrade/pages/pagev5/default.xml[]
----

This is how we migrate it to a react4xp v6 component:

First let's handle the controller which becomes a processor, the most important prop to pass from the processor is the regionsData.
Notice how we change `regionsData` to `regions`, this is because the new Regions React component is expecting it along with componentRegistry.

.src/main/resources/react4xp/components/page/PageProcessor.ts
[code,TypeScript]
----
include::{snippet}appendix/upgrade/pages/pagev6/PageProcessor.ts[]
----

Next we need to change out the part `default.tsx` with a component `page.tsx`, which is very similar except that we pass `regions` to the `Regions` react component.

.src/main/resources/react4xp/components/page/Page.tsx
[code,TypeScript]
----
include::{snippet}appendix/upgrade/pages/pagev6/Page.tsx[]
----

For XP to see it we need to keep the xml file, but we will change the name to `Page.xml` and add a description to it.
This way we can call on it using a descriptor in the component registry and data fetcher.

.src/main/resources/site/pages/Page/Page.xml
[code,xml]
----
include::{snippet}appendix/upgrade/pages/pagev6/Page.xml[]
----

Let's add it to componentRegistry and dataFetcher, this is done in the same way as we did with the part.

.src/main/resources/react4xp/componentRegistry.ts
[code,TypeScript]
----
include::{snippet}appendix/upgrade/pages/pagev6/componentRegistry.tsx[]
----

.src/main/resources/react4xp/dataFetcher.ts
[code,TypeScript]
----
include::{snippet}appendix/upgrade/pages/pagev6/dataFetcher.ts[]
----

Now we have a fully functional page component that is using the new regions and component registry.

[[migrate-layout]]
== Layouts

Lastly we need to migrate the layout, this is done in a similar way to the page.

Your current layout part might look something like this:
.src/main/resources/site/layouts/twoColumns/twoColumns.tsx

[code,typeScript]
----
include::{snippet}appendix/upgrade/layouts/layoutv5/twoColumns.tsx[]
----

with a controller like this:
.src/main/resources/site/layouts/twoColumns/twoColumns.ts

[code,TypeScript]
----
include::{snippet}appendix/upgrade/layouts/layoutv5/twoColumns.ts[]
----

And an xml like this:

.src/main/resources/site/layouts/twoColumns/twoColumns.xml
[code,xml]
----
include::{snippet}appendix/upgrade/layouts/layoutv5/twoColumns.xml[]
----

Similar to the page, we need to implement a processor, and a component.

.src/main/resources/react4xp/components/layouts/TwoColumnProcessor.ts
[code,TypeScript]
----
include::{snippet}appendix/upgrade/layouts/layoutv6/TwoColumnProcessor.ts[]
----

The Layout component is depending on the `Regions` like the page, so we need to pass the `regions` prop to it.

.src/main/resources/react4xp/components/layouts/TwoColumn.tsx
[code,TypeScript]
----
include::{snippet}appendix/upgrade/layouts/layoutv6/TwoColumn.tsx[]
----

We are keeping one more prop for layout, we use this `tags: 'section'` to target the layout with our css module.

.src/main/resources/components/layouts/twoColumn.css
[code,css]
----
include::{snippet}appendix/upgrade/layouts/layoutv6/TwoColumn.module.css[]
----

We need to add the layout to the component registry and data fetcher, this is done in the same way as we did with the part and page.

.src/main/resources/react4xp/componentRegistry.ts
[code,TypeScript]
----
include::{snippet}appendix/upgrade/layouts/layoutv6/componentRegistry.tsx[]
----

.src/main/resources/react4xp/dataFetcher.ts
[code,TypeScript]
----
include::{snippet}appendix/upgrade/layouts/layoutv6/dataFetcher.ts[]
----

And finally we need to update the xml file to match the descriptor, this is done in the same way as the page.

.src/main/resources/site/layouts/TwoColumn/TwoColumn.xml
[code,xml]
----
include::{snippet}appendix/upgrade/layouts/layoutv6/TwoColumns.xml[]
----

Now we have a fully functional layout component that is using the new regions and component registry.

(Migrate thymeleaf etc, minimal example) 0

And just like that we have not only upgraded the old component, but also made it compatible with the new ones!