= React4XP - Configuration - Run time
:toc: right

== Application configuration file

$XP_HOME/config/<app.name>.cfg

{zwsp} +

[[ssrMaxThreads]]
=== ssrMaxThreads

.$XP_HOME/config/<app.name>.cfg:
[source,cfg,options="nowrap"]
----
react4xp.ssr.maxThreads = 5
----

If this override value is not set, the number of threads (<<api#renderers, renderers>>) used for simultaneous SSR requests is determined by java, by...

[source,java,options="nowrap"]
----
Runtime.getRuntime().availableProcessors()
----

...but `ssrMaxThreads` sets this number manually instead.


{zwsp} +

=== serveGlobals

React4xp builds a globals bundle, which MUST contain all assets NEEDED to render
server-side. By default it contains react and react-dom, but more assets can be
added.

By default the globals bundle is also provided to the client-side, but you can
disable the serving of the globals bundle to the client-side by adding the
following to ${XP_HOME}/config/${app}.cfg.

```${XP_HOME}/config/${app}.cfg
	react4xp.serveGlobals = false
```

Note: Keep in mind the assets in the globals bundle are still REQUIRED for
clientSide rendering to work, so you have to provide those assets by other
means, for example via CDN.
