= React4xp, lesson 4: defining your own source structure
:toc: right
:toclevels: 2
:imagesdir: media/

{zwsp} +

== Previously:

====== link:index.html#introduction[Introduction]

{zwsp} +
Basic lessons:

====== 1. link:1-hello-react.html#hello_react_page[Hello React: server and clientside]
====== 2. link:2-editorial-data-and-props.html#editorial_props[Editorial data and props]
====== 3. link:3-pages-parts-and-regions.html#xp_pages_parts[XP Pages, Parts, Regions and Content]

{zwsp} +

== {zwsp} +

{zwsp} +
{zwsp} +

[[free_structure]]
image:react4xp.svg[title="React4xp logo",width=256px]

{zwsp} +

== 4. FREE SOURCE STRUCTURE

So far, every time we've referenced a _.jsx_ react component from react4xp in a controller, we've used a `component` object in the _entry_ argument of `React4xp.render`. This is just a shortcut, and it depends on an "XP-conventional" naming regime to work: the _.jsx_ source file must be in the same folder as the controller, and have the same name.

It doesn't have to be that way. In this example, we'll take a look at which react components are available to `React4xp.render` - called *entries* in react4xp - and how to reference them, whatever they're called and wherever they're located.

A link:#entries_and_jsxpath[detailed summary] follows after the examples.

{zwsp} +

=== Below _site/_

Below the folder _src/main/resources/site/_, all source files with the extension _.jsx_ are detected at compile-time and available as entries to react4xp. If you take the *path relative to _resources/_* and the file name without the extension, you get a string that can be used to point react4xp to that react component:

- `"site/parts/hello-react/hello-react"` -> _src/main/resources/site/parts/hello-react/hello-react.jsx_
- `"site/parts/color/color"` -> _src/main/resources/site/parts/color/color.jsx_
- `"site/parts/color/differentEntry"` -> _src/main/resources/site/parts/color/differentEntry.jsx_

...etc.

These strings are called *jsxPaths* in react4xp, and they can be used directly in controllers as the _entry_ argument. For example in the link:#color_part_controller[_color_ Part controller] from before:

.site/parts/color/color.es6
[source,javascript,options="nowrap"]
----
React4xp.render(
    component,
    props,
    request,
    options
);
----

...is equivalent to:

[source,javascript,options="nowrap"]
----
React4xp.render(
    "site/parts/color/color",
    props,
    request,
    options
);
----

And so on. Calling the _.jsx_ source file something else, or having it in a different folder, is fine as long as you refer it correctly like this.

NOTE: _jsxPaths_ are name strings, not relative paths! You can't refer to _color.jsx_ from _color.es6_ as `"color"` or `"./color"` etc.

TIP: If you look at the rendered HTML output in page source, you can see React4xp using the jsxPaths to refer to the compiled assets from the client - even if you used the `component` object in the _entry_ argument.

TIP: All the _entries_ in your project are listed with their _jsxPath_ after compilation, in _build/resources/main/assets/react4xp/entries.json_.


{zwsp} +

=== Below _react4xp/_
If you just want to keep your react components out of the regular XP file structure in _site/_ and be independent of the structure of Parts, Pages etc, the folder _src/main/resources/react4xp/_ is meant for that. Here's how (assuming you're generally following link:https://github.com/enonic/lib-react4xp/blob/0.9.0/README.adoc#setup-option-2-using-react4xp-in-an-existing-project[the recommended setup pattern] used in the react4xp starter):

Open _react4xp.properties_ in the project root, and look for the property `entryDirs`. This is a (comma-separated) list of folder names *relative to the _react4xp/_ folder*. React4xp comes with a built-in suggestion here: `entryDirs = entries`. This means that all _.jsx_ (and _.js_ and _.es6_) source files below _src/main/resources/react4xp/entries_ will become entries: react components available to react4xp.

They will get a *_jsxPath_ relative to the closest _entryDirs_ folder*.

So for example if `entryDirs = entries`, then the closest _entryDirs_ folder is _src/main/resources/react4xp/entries_, and any XP controller can render _src/main/resources/react4xp/entries/subFolder/myEntry.jsx_ like this:

[source,javascript,options="nowrap"]
----
React4xp.render(
    "subFolder/myEntry",
    props,
    request,
    options
);
----

TIP: *Under the _site/_ folder, entry source files must have the extension _.jsx_*. This is because regular XP source files can have _.js_ and _.es6_ extensions, and must be separated since the compilation and handling is very different. However, *under the _entryDirs_ folder(s), entries can have _.js_ and _.es6_ extensions too!*

NOTE: React4xp doesn't currently separate between different _entryDirs_, they behave as one. So if `entryDirs = entries,moreEntries` then _react4xp/entries/foo/bar.jsx_ and  _react4xp/moreEntries/foo/bar.jsx_ will get the same _jsxPath_: `"foo/bar"`. Beware of *namespace collisions*; you won't be able to refer to both.


{zwsp} +

=== Anywhere else

The _entryDirs_ are paths relative to _src/main/resources/react4xp/_, so just use relative _entryDirs_ if you need entries outside of that.

For example, say you've added an NPM package _externalComponents_ with react components in a _comps_ subfolder, and you want to use them as entries. Simply add it to _entryDirs_:

.react4xp.properties
[source,options="nowrap"]
----
entryDirs=entries,../../../../../node_modules/externalComponents/comps
----

(Or replace _entries_ if you're not using it, of course)


== {zwsp} +

Okay, time to move on to the next example and lesson!

[.right]
-> 5. link:5-custom-flow-syntax.html#custom_flow[Custom flow syntax]

{zwsp} +
{zwsp} +

== Next: advanced lessons

====== 5. link:5-custom-flow-syntax.html#custom_flow[Custom flow syntax]
====== 6. link:6-imports-and-dependency-chunks.html#imports_chunks[Imports, chunks, config, webpack]

== {zwsp} +

== Details and API

Need to go deeper? Here are some more detailed explanations and API documentaion:

====== link:entries-and-jsxpath.html#entries[Entries]
====== link:entries-and-jsxpath.html#jsxPath[JsxPath]
====== link:entries-and-jsxpath.html#chunks[Optimizing dependency chunks]
====== link:faq.html#faq[FAQ]

{zwsp} +

====== link:api.html#_react4xp_render[React4xp.render]

{zwsp} +
{zwsp} +
