= React4XP - API reference
:toc: right
:imagesdir: media/

The react4xp library (link:https://market.enonic.com/vendors/enonic/react4xp-lib[Enonic Market]) exposes a couple of methods that can be run from XP controllers.

For more instructions on how to installing the library locally or insert it into your project, see link:https://github.com/enonic/lib-react4xp#readme[the library docs] at github.

[[api]]
== Import in a controller

[source,javascript,options="nowrap"]
----
const React4xp = require('/lib/enonic/react4xp');
----

{zwsp} +

[[react4xp_render]]
== React4xp.render

All-in-one shorthand function for a lot of use cases. Covers both client- and serverside rendering.

Inserts a react component into an (optional) pre-existing HTML string and adds any necessary page contributions to make all work: links to assets, both shared and specific to the entry, and a client-side JS call (`.render` or `.hydrate` in the link:https://www.npmjs.com/package/react4xp-runtime-client[client wrapper]) that activates the react component in the browser.

{zwsp} +

[.lead]
Signature

The signature is analogous to thymeleaf's familiar `render(view, model)`. But there are two extra parameters, and a full XP response object is returned:

[source,javascript,options="nowrap"]
----
{body, pageContributions} = React4xp.render(entry, props, request, options);
----

{zwsp} +

[.lead]
Parameters

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name   | Type   | Description
| `entry` | string or component object, mandatory | Reference to an <<entries#, entry>>: the react component to be rendered. <<jsxpath#, JsxPath>> reference - or if the entry is a JSX file with the _same name_ in the _same folder_ as the controller, you can use a `portal.getComponent()` object here. Corresponds to the template argument in `thymeleaf.render`.
| `props` | object, optional | Data model passed into the react component. JS object must be serializable (no functions can be passed). Corresponds to the model argument in `thymeleaf.render`.
| `request` | link:https://developer.enonic.com/docs/xp/stable/framework/http[XP request object], optional (but _mandatory for react activation_) | Include to detect the rendering mode inside/outside Content Studio: inside Content Studio there should be only a static serverside-rendering, no browser react activation (or client-side rendering), only returning get an HTML visualization with the initial `props`. Special case: if `request` is not an object but omitted/falsy, page-contributions rendering is _completely skipped_. In this case, the _options_ argument (below) is still valid: any added `body` there will still serve as a container for the rendered output from this call, and any `pageContributions` inside _options_ are still added and returned.

| `options` | object, optional | Additional options to control the rendering. All of them are optional within this object:

[%header,cols="1%,1%,1%,96%a"]
[frame="topbot"]
[grid="none"]
[caption=""]
.Properties
!===
! Name        ! Type   ! Default ! Description
! `id` ! string! Unique string (random) !  ID of the component, targeting the ID of an element in `body` (below): react will render into that container element. Should be a unique ID within the entire HTML document.

If `id` is missing, a random ID is generated.
! `body` ! string: valid HTML ! `<div>` with matching `id` ! HTML to serve as container for the react content. Can be a hardcoded string, come from a thymeleaf/mustache/XSLT render, or any source.  When server-side rendering, the rendered output will be inserted into the matching-`id` element inside here (replacing whatever was already in that element), and everything (container `body` with rendered content in it) is returned as one HTML string. When client-side rendering, this insertion happens in the browser.

If no `body` is supplied, an empty `<div>` element with an ID matching `id` is generated and used as container.

If a `body` is supplied but it doesn't contain any element with a matching `id`, an extra matching-`id` `<div>` element will be generated and inserted into `body` - as a child of the root element of `body` and after any other content that's already there.
! `pageContributions` ! object: valid link:https://developer.enonic.com/docs/xp/stable/cms/contributions[XP page contributions] ! ! If you already have some page contributions you want to add to the output of this rendering, add them here. These added page contributions will be added _before_ the ones that will be rendered (within each section `headBegin`, `bodyEnd` etc).
! `clientRender` ! boolean ! false ! Switch between clientside and servierside rendering, on this particular rendering. Other renderings are not affected, even within the same controller or using the same entry more than once.

If `false` / falsy or omitted, you get serverside rendering and the returned object will contain an HTML representation of the react component with the initial `props`, and page contributions will make the client call `.hydrate`.

If `true` / truthy, the server-side rendering is skipped for this particular rendering. The client will call `.render`.

This *only applies in live mode and previews*: inside _edit_ or _browse_ modes in Content Studio, you still only get a static server-side rendered representation).
!===

|===

{zwsp} +

[.lead]
Returns

Returns an link:https://developer.enonic.com/docs/xp/stable/framework/http[XP response object] with these main attributes:

[%header,cols="1%,1%,98%a"]
[frame="none"]
[grid="none"]
|===
| Name   | Type   | Description
| `body` | string, rendered HTML | HTML output. Surrounding HTML from any input `options.body` (or just a surrounding placeholder `<div>`), and if serverside rendering, the HTML from the rendered react component is included inside the target container in the surrounding HTML.
| `pageContributions`| object | Regular link:https://developer.enonic.com/docs/xp/stable/cms/contributions[XP page contributions]. Includes everything the browser needs to activate (or client-side render) the react component: script tags with urls to auto-compiled assets for the entry and its dependencies, a client-side react4xp wrapper asset and an activating client-wrapper call. Urls point to react4xp's own optimized asset services. Also included before this, are any input `options.pageContributions`.
|===

{zwsp} +
{zwsp} +
