= React4XP - API reference
:toc: right
:imagesdir: media/

[[api]]

[[react4xp_render]]
== React4xp.render

React4xp's `.render` is a one-in-all shorthand function for a lot of use cases. Basically, take any HTML string and pass it through `.render` as a `body` option, and react4xp will insert the react component into the HTML string and add any necessary page contributions to make it all work.

{zwsp} +

The *signature* is analogous to thymeleaf's familiar `render(view, model)`. But there are two extra parameters, and a full XP response object is returned:

[source,javascript,options="nowrap"]
----
{body, pageContributions} = React4xp.render(entry, props, request, options);`
----

{zwsp} +

=== Parameters

- `entry` (mandatory, string or component object): the reference to the "template"; the react component to be rendered. <<jsxpath#, jsxPath>> reference to an <<entries#, entry>> - or if the entry is a JSX file with the _same name_ in the _same folder_ as the controller, you can use a `portal.getComponent()` object here.
- `props` (optional object, must be serializable): data model passed into the react component.
- `request` (link:https://developer.enonic.com/docs/xp/stable/framework/http[XP request object], kind of optional, but _mandatory for react activation_): This is to keep the component rendered static and serverside-render if the rendering happens inside XP content studio. No browser react activation (or client-side rendering) happens inside content studio, you only get a HTML visualization from the initial `props` rendered on the server. Special case: if `request` is omitted/falsy, page-contributions rendering is completely skipped. Note: the .render _options_ argument is still valid: the rendered static HTML is still inserted into the HTML from the added `body`, and `pageContributions` inside _options_ are still added.
- `options` (optional object): additional options to control the rendering:

** `id` (string): ID of the component, matching the ID of an element in `body`. React will render into that container element, replacing whatever was already there. If missing, a random ID is generated.
** `body` (string): HTML string, a base for the returned `body`. Can be a hardcoded string, or come from a thymeleaf/mustache/XSLT render, and so on. Just make sure the `id` option matches an HTML id here (what happens if not? React4xp creates a target element with that ID, last in the root element of `body`). If there's no `body` option, a matching-ID `<div>` target container is generated.

** `pageContributions` (object): you might already have some page contributions you want to return together with the ones generated by react4xp. Same way as with `body`, just add them here to pass them through `render`. Order: the ones you add here are output before the ones rendered.
** `clientRender` (boolean): if `true` (truthy, actually), the server-side rendering is skipped (in live mode and previews. Inside content studio's browser or edit modes, you still only get a static server-side rendered representation).

=== Return

Returns an link:https://developer.enonic.com/docs/xp/stable/framework/http[XP response object] with these main attributes:

- `body`: rendered HTML string. When server-side rendered, the whole HTML is inserted into the matching-id element inside the `body` option (if the `body` option is added. If not, a surrounding `<div>` is used). When client-side rendered, no HTML is inserted into `body` (or the generated container) - that's left to the client.
- `pageContributions`: a regular link:https://developer.enonic.com/docs/xp/stable/cms/contributions[XP page contributions] object. Includes everything the browser needs to activate (or client-side render) the react component: auto-compiled assets for the entry (_hello-react.js_ in this example) and whatever it may depend on (most importantly, react and react-dom in an _externals_ asset), and a client-side react4xp wrapper asset. These are all optimized and served to the client by react4xp services.

{zwsp} +
{zwsp} +
