= Application commons
:toc: right
:imagesdir: media/
:sourcedir: ../src/main/resources/
:snippet: ../code-samples/code-snippets/

In this chapter you will add global styling and a footer component to the front-end.

== Global CSS

Our application looks a bit bland, let's add the finishing touches to make it look more appealing.
 For this we are going to add a global CSS file, this allows us to avoid repeating general styling in each component.

Add global CSS file to the component directory:

.react4xp/components/globalStyles.css
[source,CSS]
----
include::../code-samples/code-snippets/App-layout/globalStyles.css[]
----

Add your global CSS file to the app:

.react4xp/entries/App.tsx
[source,TypeScript]
----
import '../components/globalStyles.css';
----

== Footer component

A footer component is like an autograph, it is a signature of the author usually visible on every page of the application.

Add the footer component within a common directory:

.react4xp/components/common/Footer.tsx
[source,TypeScript]
----
include::{sourcedir}react4xp/components/common/Footer.tsx[]
----

=== CSS module

The footer component also has a dedicated CSS module, which allows targeted styling without conflicts with other components and classes.

Add the CSS module to the common directory:

.react4xp/components/common/Footer.module.css
[source,CSS]
----
include::{snippet}App-layout/Footer.module.css[]
----

Add the footer to your app:

.react4xp/entries/App.tsx
[source,TypeScript]
----
include::{snippet}App-layout/App.tsx[]
----


=== Asset URL

Lastly we need to be able to display a logo in the footer!
To do this we use assetUrl() which is a function that generates a URL pointing to a static file.

You might have noticed that the footer component does not have its own processor as it is a static component, we need to add a commonProcessor to the app to provide the assetUrl function.
You can also add other common functions here if needed.

.react4xp/components/common/CommonProcessor.ts
[source,TypeScript]
----
include::{sourcedir}react4xp/components/common/CommonProcessor.ts[]
----

Lastly add the common processor to the data fetcher:

.react4xp/dataFetcher.ts
[source,TypeScript]
----
include::{snippet}App-layout/dataFetcher.ts[]
----

Sweet!
Now we have a footer component that is visible on all pages in the application, and it is styled using a CSS module.

== Next

You are on a roll, in the next chapter we'll be <<render-content#, rendering content>>.
