= Server side TSX/JSX with React4XP
:toc: right
:imagesdir: media/

This tutorial will show you step-by-step how to build XP sites and apps with React rendering, helping you kickstart a React4xp project of your own.

{zwsp} +

image:react4xp.svg[title="React4xp logo",width=256px]


{zwsp} +

== Upgrade

If you are upgrading to lib-react4xp 3.x.x please ready this <<upgrade#,upgrade guide>>.

== Introduction

[NOTE]
====
A little bare-bone knowledge of link:https://reactjs.org/tutorial/tutorial.html[React] and link:https://developer.enonic.com/start[Enonic XP] is recommended.
====


React4XP is a library (with a companion build structure) that facilitates advanced use of React in Enonic XP, and:

* enables you to use TSX/JSX as a templating language, similar to other XP templating engines
* supports isomorphic client- or serverside rendering and hydration,
* handles build flow and compilation with automated optimized asset serving
* is modular and flexible enough to cover many advanced use cases


{zwsp} +

== Tutorial overview

After <<setup#, getting set up>>, we'll begin with *3 basic lessons* - just the minimum of what you need to get started:

- <<hello-react#, Hello React: server and clientside>>: Meet the React4xp library and display a react component from content studio - first serverside rendered, then clientside.
- <<editorial-data-and-props#, Editorial data and props>>: Use props to pass data - for example editorial data from XP - into the react component.
- <<pages-parts-and-regions#, XP Pages, Parts, Regions and Content>>: Taking more advantage of the page-building powers in Content Studio - react rendering from any XP controller.


{zwsp} +

The next 5 lessons present a few more *advanced usages*:

- <<source-file-structure#, Free source file structure>>: Which react components are available to React4xp (called _entries_), and how to reference them.
- <<custom-flow-syntax#, Custom flow syntax>>: A more detailed and explicit syntax, for when your controller needs more control.
- <<imports-and-dependency-chunks#, Imports, chunks, config, webpack>>: Importing things into your entries, and controlling the compilation rules and output.
- <<guillotine#, Headless, part 1>>: Introduction of how to use React4xp in a headless-CMS context: set up a data endpoint that serves XP content as pure data, and have the already-rendered React4xp components add more content asynchronously with that content data.
- <<webapp#, Headless, part 2>>: "pure headless" with preview - standalone webapps that take the same React4xp components out of Content Studio, and render the content with assets and data served from anywhere.

{zwsp} +

== Details
If you *need to go deeper* after going through the lessons, the most important concepts you'll encounter along the way are explained on pages of their own:

- <<entries#, Entries>>
- <<jsxpath#, JsxPath>>
- <<chunks#, Optimizing dependency chunks>>

There's also an <<api#, API reference>> for the methods that the react4xp library (link:https://market.enonic.com/vendors/enonic/react4xp-lib[_lib-react4xp_]) exposes to the XP controllers:

- <<api#react4xp_render, React4xp.render>>
- <<api#react4xp_object, React4xp data objects>>

{zwsp} +

== Issues?
Questions, bug reports or suggestions are welcome!

- link:https://github.com/enonic/lib-react4xp/issues?q=is%3Aissue+is%3Aopen+label%3Abug[Known bugs we're working on] - and a few workarounds
- link:https://github.com/enonic/lib-react4xp/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement[Future improvements, requested features]
- link:https://discuss.enonic.com[The Enonic Forums]
