= Server side React with the Enonic framework - React4XP
:toc: right
:imagesdir: media/

Hands on tutorial for rendering Enonic sites and pages with JSX/TSX

image:react4xp.svg[title="React4xp logo",width=256px]

== Introduction

[NOTE]
====
A little bare-bone knowledge of link:https://reactjs.org/tutorial/tutorial.html[React] and link:https://developer.enonic.com/start[Enonic XP] is recommended before you dive into this tutorial.
====

React4XP facilitates advanced use of React when rendering with Enonic XP

* enables you to use TSX/JSX as a templating language, similar to other XP templating engines
* supports isomorphic client- or serverside rendering and hydration,
* handles build flow and compilation with automated optimized asset serving
* is modular and flexible enough to cover many advanced use cases

                                                      
== Tutorial overview

After <<setup#, getting set up>>, you start with *three basic lessons*:

- <<hello-react#, Hello React: server and clientside>>: Meet the React4xp library and display a react component from content studio - first serverside rendered, then clientside.
- <<editorial-data-and-props#, Editorial data and props>>: Use props to pass data - for example editorial data from XP - into the react component.
- <<pages-parts-and-regions#, XP Pages, Parts, Regions and Content>>: Taking more advantage of the page-building powers in Content Studio - react rendering from any XP controller.

The following five lessons present a more *advanced use cases*:

- <<source-file-structure#, Free source file structure>>: Which react components are available to React4xp (called _entries_), and how to reference them.
- <<custom-flow-syntax#, Custom flow syntax>>: A more detailed and explicit syntax, for when your controller needs more control.
- <<imports-and-dependency-chunks#, Imports, chunks, config, webpack>>: Importing things into your entries, and controlling the compilation rules and output.
- <<client-side#, Client-side rendering, part 1>>: Introduction of how to use React4xp client-side, set up a data endpoint that serves XP content as pure data, and have the already-rendered React4xp components add more content asynchronously with that content data.
- <<standalone#, Standalone mode>>: Here we build a webapp that take the same React4xp components out of Content Studio, and render the content with assets and data served from anywhere.

== Dive deeper
Have an urge for details beyond the basic tutorial, check out the following:

- <<entries#, Entries>>
- <<jsxpath#, JsxPath>>
- <<chunks#, Optimizing dependency chunks>>
- <<api#, API reference>> for the (link:https://market.enonic.com/vendors/enonic/react4xp-lib[React4XP library]).

== Issues?
Questions, bug reports or suggestions are welcome!

- link:https://github.com/enonic/lib-react4xp/issues?q=is%3Aissue+is%3Aopen+label%3Abug[Known bugs we're working on] - and a few workarounds
- link:https://github.com/enonic/lib-react4xp/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement[Future improvements, requested features]
- link:https://discuss.enonic.com[The Enonic Forums]
