= React4XP - Building React sites with the Enonic framework
:toc: right
:imagesdir: media/

Hands on introduction to the React4XP framework - rendering components with JSX/TSX

== Introduction

[NOTE]
====
It is recommended that you have completed the https://developer.enonic.com/start[My First Site] tutorial, as well as having a some knowledge of https://reactjs.org/tutorial/tutorial.html[React] before you dive into this tutorial.
====

image:react4xp.svg[title="React4xp logo",width=256px]


React4XP facilitates advanced use of React when rendering pages with the Enonic framework.

* enables you to use TSX/JSX as a templating language, similar to other XP templating engines
* supports isomorphic server side and client side rendering with hydration
* handles build flow with automated optimized asset serving
* is modular and flexible enough to cover many advanced use cases

                                                      
== Tutorial overview

After <<setup#, getting set up>>, you start with *three basic lessons*:

- <<hello-react#, Hello React: server and clientside>>: Meet the React4xp library and display a react component from content studio - first serverside rendered, then clientside.
- <<editorial-data-and-props#, Editorial data and props>>: Use props to pass data - for example editorial data from XP - into the react component.
- <<pages-parts-and-regions#, XP Pages, Parts, Regions and Content>>: Taking more advantage of the page-building powers in Content Studio - react rendering from any XP controller.

The following five lessons present a more *advanced use cases*:

- <<source-file-structure#, Free source file structure>>: Which react components are available to React4xp (called _entries_), and how to reference them.
- <<custom-flow-syntax#, Custom flow syntax>>: A more detailed and explicit syntax, for when your controller needs more control.
- <<imports-and-dependency-chunks#, Imports, chunks, config, webpack>>: Importing things into your entries, and controlling the compilation rules and output.
- <<client-side#, Client-side rendering, part 1>>: Introduction of how to use React4xp client-side, set up a data endpoint that serves XP content as pure data, and have the already-rendered React4xp components add more content asynchronously with that content data.
- <<standalone#, Standalone mode>>: Here we build a webapp that take the same React4xp components out of Content Studio, and render the content with assets and data served from anywhere.

== Dive deeper
Have an urge for details beyond the basic tutorial, check out the <<appendix#, Appendix section>>.

== Issues?
Questions, bug reports or suggestions are welcome!

- link:https://github.com/enonic/lib-react4xp/issues?q=is%3Aissue+is%3Aopen+label%3Abug[Known bugs we're working on] - and a few workarounds
- link:https://github.com/enonic/lib-react4xp/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement[Future improvements, requested features]
- link:https://discuss.enonic.com[The Enonic Forums]
