= React4XP - Server Side React sites on Enonic
:toc: right
:imagesdir: media/

Build server-side rendered React websites with without introducing a 3rd party front-end framework

== Introduction

[NOTE]
====
It is recommended that you have had a look at https://developer.enonic.com/start[My First Site], as well as basic https://reactjs.org/tutorial/tutorial.html[React] knowledge before you dive into this tutorial.
====

image:react4xp.svg[title="React4xp logo",width=256px]

React4XP facilitates advanced use of React within Enonic.

* 100% TSX/JSX rendering
* Single React app
* Isomorphic server side and client side rendering through hydration
* Supports Enonic page templates
* Fast and continuous builds
* Optimized static asset handling
* Flexible enough to cover many advanced use cases
                                      

== Get started

Get started by <<setup#, setting up the developer environment>>.

== Dive deeper
For details beyond the tutorial, visit the <<appendix#, Appendix section>>.

== Issues?
Questions, bug reports or suggestions are welcome!

- link:https://github.com/enonic/lib-react4xp/issues?q=is%3Aissue+is%3Aopen+label%3Abug[Known bugs we're working on] - and a few workarounds
- link:https://github.com/enonic/lib-react4xp/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement[Future improvements, requested features]
- link:https://discuss.enonic.com[The Enonic Forums]
