= Server side JSX with React4XP
:toc: right
:imagesdir: media/

{zwsp} +

[NOTE]
====
This guide expects at least a little bare-bone knowledge of link:https://reactjs.org/tutorial/tutorial.html[React] and link:https://developer.enonic.com/start[Enonic XP]. Beyond that, it's super detailed.
====

{zwsp} +
{zwsp} +

image:react4xp.svg[title="React4xp logo",width=256px]

{zwsp} +

== Introduction

This tutorial will show you step-by-step how to build XP sites and apps with React rendering, helping you kickstart a React4xp project of your own.

During this exercise you will:

- set up the starter and meet the React4xp library,
- learn how to use it to render a basic React component from any regular XP controller,
- inject editorial data into your React component,
- see how to point the controller to the React components - and where to put them in your project source,
- dig a little deeper into ways of controlling the rendering,

{zwsp} +


=== About React4XP


This starter is based on *React4XP*, which is a library (with a companion build structure) that facilitates use of React in Enonic XP, and:

* enables you to use JSX as a templating language, similar to other XP templating engines
* supports isomorphic client- or serverside rendering and hydration,
* handles build flow and compilation with automated optimized asset serving
* is modular and tweakable, making it possible to pop the hood, pick it apart and set things up your own way. Godspeed!
* is flexible enough to cover many advanced use cases,

{zwsp} +


== Docs overview

<<setup#, Project setup>>: Create a new project based on the React4XP starter.


=== Basic lessons

The first three chapters are a basic-level tutorial, just what you need to get started:


. <<hello-react#, Hello React: server and clientside>>: Display a react component from content studio, first serverside rendered, then clientside.

. <<editorial-data-and-props#, Editorial data and props>>: Insert editorial data from XP into the react component.

. <<pages-parts-and-regions#, XP Pages, Parts, Regions and Content>>: Taking more advantage of the page-building powers in Content Studio - all react rendered.


{zwsp} +

=== Advanced lessons

The next three chapters present a few more advanced usages:

[start=4]
. <<source-file-structure#, Free source file structure>>: Which react components are available to react4xp (called _entries_), and how to reference them.

. <<custom-flow-syntax#, Custom flow syntax>>: A more detailed and explicit syntax, for when you need more control.

. <<imports-and-dependency-chunks#, Imports, chunks, config, webpack>>: Importing things into your entries, and controlling the compilation rules and output.

{zwsp} +
{zwsp} +

=== Concepts

Need to go deeper? Take a look at some more detailed explanations and docs:

<<entries#, Entries>>

<<jsxpath#, JsxPath>>

<<chunks#, Optimizing dependency chunks>>

{zwsp} +

=== API

<<api#react4xp_render, React4xp.render>>

{zwsp} +
{zwsp} +

== Issues
Questions, bug reports or suggestions are welcome!

- link:https://github.com/enonic/lib-react4xp/issues?q=is%3Aissue+is%3Aopen+label%3Abug[Known bugs we're working on] - and a few workarounds
- link:https://github.com/enonic/lib-react4xp/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement[Future improvements, requested features]
- link:https://discuss.enonic.com[The Enonic Forums]

{zwsp} +
{zwsp} +
