= Server side JSX with React4XP
:toc: right
:toclevels: 2
:imagesdir: media/

{zwsp} +

[NOTE]
====
This guide expects at least a little bare-bone knowledge of link:https://reactjs.org/tutorial/tutorial.html[React] and link:https://developer.enonic.com/start[Enonic XP]. Beyond that, it's super detailed.

So it's probably fine to *focus on the code*, and just use the text for context, a closer look, and troubleshooting.

**UPDATED {docdate}:** multiple adaptations for starter and lib version 1.0.0.
====

{zwsp} +
{zwsp} +

[[introduction]]
image:react4xp.svg[title="React4xp logo",width=256px]

{zwsp} +

== Introduction

This tutorial will show you step-by-step how to build XP sites and apps with React rendering, helping you kickstart a React4xp project of your own.

During this exercise you will:

- set up the starter and meet the React4xp library,
- learn how to use it to render a basic React component from any regular XP controller,
- inject editorial data into your React component,
- see how to point the controller to the React components - and where to put them in your project source,
- dig a little deeper into ways of controlling the rendering,

{zwsp} +


=== About React4XP


This starter is based on *React4XP*, which is a library (with a companion build structure) that facilitates use of React in Enonic XP, and:

* enables you to use JSX as a templating language, similar to other XP templating engines
* supports isomorphic client- or serverside rendering and hydration,
* handles build flow and compilation with automated optimized asset serving
* is modular and tweakable, making it possible to pop the hood, pick it apart and set things up your own way. Godspeed!
* is flexible enough to cover many advanced use cases,

{zwsp} +

=== Setup: create project

Set up the starter project locally. With Enonic XP 7, run the following command:

[source,bash]
----
enonic project create -r starter-react4xp
----

Remember to create a *new XP sandbox* when completing the project wizard.

[TIP]
====
*Don't have the Enonic CLI?* Visit the https://developer.enonic.com/start[Getting started guide] to install it.

*Only want to inject react4xp into your own XP project?* The https://github.com/enonic/lib-react4xp/blob/master/README.md[lib-react4xp docs] have a section on how to do without the starter. But it's recommended to go through this introduction first.
====

{zwsp} +

=== Project structure

If you're used to working with a typical XP project using https://developer.enonic.com/templates/webpack[webpack], the structure in your project root folder will now look familiar -
the biggest news is `react4xp.properties` and the folder `resources/react4xp/`.

TIP: This is just an overview, no need to know it by heart to get started - we'll get back to all of these in more detail. For the most impatient, the takeaway is: *put your JSX source files somewhere below `react4xp/entries/` or `site/`*.

[source,files]
----
build.gradle                <!--1-->
gradle.properties
settings.gradle
package.json

react4xp.properties         <!--2-->

src/
  main/
    resources/
      react4xp/             <!--3-->
        entries/
        shared/

----

<1> A set of gradle config files and `package.json`. These define the build process and project structure, and in particular, make sure that the *lib-react4xp library* and *react4xp npm package* are installed right.
<2> `react4xp.properties`: tune the most common properties of the react4xp project.
<3> The `react4xp/` folder is opt-in: can be ignored for now, and doesn't need to contain anything. But when fine-tuning the build later in the tutorial, we'll get back to why you might find it handy to have a separate place for some of your react components (in ultra-short: the `entries\` folder is for react components that can be used directly by react4xp, the `shared\` folder is for common components imported by, and shared between, the entries).


{zwsp} +

=== Build and Deploy

To build and deploy the starter app, run this command from your shell:

[source, bash]
----
enonic project deploy
----

Accept starting the sandbox.

[NOTE]
====
To verify that your app started successfully, you should find an entry similar to this in the sandbox log:

`2019-04-09 13:40:40,765 INFO ... Application [<name.of.your.app>] installed successfully`
====

== {zwsp} +

Now you're ready to get started with the first lesson chapters.

[.right]
-> 1. <<1-hello-react#, Hello React: server and clientside>>

{zwsp} +
{zwsp} +
{zwsp} +
{zwsp} +

== Docs overview

=== The lessons

==== Basic
The first three chapters are a basic-level tutorial, just what you need to get started:

1. <<1-hello-react#, Hello React: server and clientside>>: Display a react component from content studio, first serverside rendered, then clientside.

2. <<2-editorial-data-and-props#, Editorial data and props>>: Insert editorial data from XP into the react component.

3. <<3-pages-parts-and-regions#, XP Pages, Parts, Regions and Content>>: Taking more advantage of the page-building powers in Content Studio - all react rendered.



{zwsp} +

==== Advanced

The next three chapters present a few more advanced usages:

[start=4]
4. <<4-source-file-structure#, Free source file structure>>: Which react components are available to react4xp (called _entries_), and how to reference them.

5. <<5-custom-flow-syntax#, Custom flow syntax>>: A more detailed and explicit syntax, for when you need more control.

6. <<6-imports-and-dependency-chunks#, Imports, chunks, config, webpack>>: Importing things into your entries, and controlling the compilation rules and output.

{zwsp} +
{zwsp} +

=== The details

Need to go deeper? Take a look at some more detailed explanations and docs:

==== Concepts

<<entries#, Entries>>

<<jsxpath#, JsxPath>>

<<chunks#, Optimizing dependency chunks>>

{zwsp} +

==== API

<<api#react4xp_render, React4xp.render>>

{zwsp} +
{zwsp} +

== Issues
Questions, bug reports or suggestions are welcome!

- link:https://github.com/enonic/lib-react4xp/issues?q=is%3Aissue+is%3Aopen+label%3Abug[Known bugs we're working on] - and a few workarounds
- link:https://github.com/enonic/lib-react4xp/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement[Future improvements, requested features]
- link:https://discuss.enonic.com[The Enonic Forums]

{zwsp} +
{zwsp} +
