= Setting up your project
:toc: right
:imagesdir: media/

{zwsp} +


== Create project

Set up the starter project locally, run the following command:

[source,bash]
----
enonic project create -r starter-react4xp
----

Remember to create a *new XP sandbox* when completing the project wizard.

[TIP]
====
*Don't have the Enonic CLI?* Visit the https://developer.enonic.com/start[Getting started guide] to install it.

*Only want to inject react4xp into your own XP project?* The https://github.com/enonic/lib-react4xp/blob/master/README.md#setup-option-2-using-react4xp-in-an-existing-project[lib-react4xp docs] have a section on how to do without the starter. But it's recommended to go through this introduction first.
====

{zwsp} +

== Project structure

If you're used to working with a typical XP project using https://developer.enonic.com/templates/webpack[webpack], the structure in your project root folder will now look familiar -
the biggest news are _react4xp.config.js_ and the folders _src/main/resources/react4xp/_ and _src/main/resources/headless_.

TIP: This is just an overview, no need to know it by heart to get started - we'll get back to all of these in more detail. For the most impatient, the takeaway is: *put your JSX source files somewhere below _react4xp/entries/_ or _site/_*.

[source,files]
----
build.gradle                    <!--1-->
gradle.properties
settings.gradle
package.json

react4xp.config.js              <!--2-->

src/
  main/
    resources/
      react4xp/                 <!--3-->
        entries/
        shared/
      headless/
        guillotineApi.es6       <!--4-->
        guillotineRequest.es6

----

<1> A set of gradle config files and _package.json_. These define the build process and project structure, and in particular, make sure that the *lib-react4xp library* and *@enonic/react4xp npm package* are installed right.
<2> _react4xp.config.js_: Place to add extra globals and tune the most common properties of the React4xp project.
<3> The _react4xp/_ folder is opt-in: can be ignored for now, and doesn't need to contain anything. But when fine-tuning the build later in the tutorial, we'll get back to why you might find it handy to have a separate place for some of your react components (in ultra-short: the _entries/_ folder is for react components that can be used directly by React4xp, the _shared\_ folder is for common components imported by, and shared between, the entries).
<4> Under _headless/_, the starter includes two wrappers that make it easier to use the optional guillotine api for using React4xp in a <<guillotine#, headless context>>.

{zwsp} +

== Build and Deploy

1. *Run the build process:*
+
[source, bash]
----
enonic project deploy
----
+
NOTE: With versions _1.1 and below_ of the React4xp starter, you must run `npm install` before this; _gradle.build_ imports some extra react4xp-related gradle tasks from link:https://www.npmjs.com/package/react4xp[node_modules/@enonic/react4xp/]. At version 1.2 and above, _build.gradle_ in the starter is set up to auto-check and install.
+
2. *Start the XP sandbox* (or accept when the enonic CLI asks you to).
+
[NOTE]
====
To verify that your app started successfully, you should find an entry similar to this in the sandbox log:

`2019-04-09 13:40:40,765 INFO ... Application [<name.of.your.app>] installed successfully`
====

{zwsp} +

Now you're ready to get started with the first lesson chapters.

[.right]
-> <<hello-react#, Hello React>>

{zwsp} +
{zwsp} +
