= Type mappings
:toc: right
:imagesdir: media/

It's time to build your first component - let's focus on rendering persons.

== Datafetcher

. TODO

== Component

. TODO

Right of the bat, start by adding a React component (tsx) file to your project:

TODO: Place elsewhere

./src/main/resources/react4xp/entries/hello-react.tsx
[source,TSX]
----
include::../src/main/resources/react4xp/entries/hello-react.tsx[]
----

<1> React component that will render "Hello React4XP!"
<2> The `export default` line is required, it _may_ take a props object and _must_ return a react component.

This component will be executed, and rendered server-side.



== Component registry

. TODO


== React template

=== XP controller

To trigger the rendering, we'll use a standard Enonic controller (ts). Add the following file to your app:

TODO: This whould now using mappings + app.ts

./src/main/resources/controllers/hello-react.ts
[source,TypeScript]
----
include::../code-samples/hello-react.ts[]
----

<1> XP controller implementing HTTP get.
<2> ID for the react app (TODO)
<3> React templates placed in `src/resources/main/react4xp/entries` may simply be referenced by their name, using a concept we call <<appendix/jsxpath#, jsxPath>>).
<4> The output of React4XP render() is a regular https://developer.enonic.com/docs/xp/stable/framework/http[XP response object].
<5> Bootstrap markup for the React application 


=== Controller mapping

TODO: This should be just a note, telling how app.ts is kickstarted.

By adding a mapping to `site.xml` - our controller will be invoked for sites where the application is deployed:

./src/main/resources/site/site.xml
[source,XML]
----
include::../src/main/resources/site/site.xml[]
----



== Next

What a start, coming up, let's make the component come alive on the <<hydration#, client side>> as well.